# This file is not used anymore and is left for reference. 
name: Elastic Dev Docs Builder (Deprecated)
on:
  workflow_call:
    secrets:
      VERCEL_GITHUB_TOKEN:
        description: 'A GitHub PAT with repo scope'
        required: true
      VERCEL_TOKEN:
        description: 'Vercel API token, account level'
        required: true
      VERCEL_ORG_ID:
        description: 'Vercel ORG token, org level'
        required: true
      VERCEL_PROJECT_ID_DOCS_DEV:
        description: 'Vercel PROJECT token, project level'
        required: true

jobs:
  build-dev-docs:
    name: Build internal docs
    runs-on: ubuntu-latest
    steps:
      - name: Skip retired Docsmobile publishing
        run: echo "Docsmobile publishing is frozen."
