name: builder

on:
  workflow_call:
    inputs:
      prebuild:
        type: string
      project-name:
        type: string
      repo:
        type: string
    secrets:
      VERCEL_GITHUB_TOKEN:
        description: 'A GitHub PAT with repo scope'
        required: true
      VERCEL_TOKEN:
        description: 'Vercel API token, account level'
        required: true
      VERCEL_ORG_ID:
        description: 'Vercel ORG token, org level'
        required: true
      VERCEL_PROJECT_ID_DOCS_DEV:
        description: 'Vercel PROJECT token, project level (deprecated)'
      VERCEL_PROJECT_ID_DEV_PREVIEW_DOCS:
        description: 'Vercel PROJECT token, project level'

jobs:
  preview:
    name: doc builder
    runs-on: ubuntu-latest
    steps:
      - name: Skip retired Docsmobile publishing
        run: echo "Docsmobile publishing is frozen."
